version: '3.8'
x-airflow-common:
  &airflow-common
  build:
    context: ./containers/airflow/
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: ${AIRFLOW__CORE__EXECUTOR}
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${AIRFLOW__CORE__SQL_ALCHEMY_CONN}
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
    AIRFLOW_CONN_POSTGRES_DEFAULT: ${AIRFLOW_CONN_POSTGRES_DEFAULT}
    MINIO_ROOT_USER: ${MINIO_ROOT_USER}
    MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    MINIO_HOST: ${MINIO_HOST}
    MINIO_PORT: ${MINIO_PORT}
    MINIO_ENDPOINT: ${MINIO_ENDPOINT}

  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./tests:/opt/airflow/tests
    - ./src:/opt/airflow/src
    - ./utils:/opt/airflow/utils
    - ./database:/opt/airflow/database
  user: "${AIRFLOW_UID}:${AIRFLOW_GID}"
  depends_on:
    postgres:
      condition: service_healthy

services:
  airflow-webserver:
    <<: *airflow-common
    container_name: webserver
    command: webserver
    ports:
      - 8080:8080
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:8080/health"
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    mem_limit: 4gb
    cpu_count: ${CPU_COUNT}
    cpus: 0.7
  
  airflow-scheduler:
    <<: *airflow-common
    container_name: scheduler
    command: scheduler
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"'
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    mem_limit: 4gb
    cpu_count: ${CPU_COUNT}
    cpus: 0.7

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    command: version
    mem_limit: 2gb
    cpu_count: ${CPU_COUNT}
    cpus: 0.7
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD}

  postgres:
    container_name: postgres
    image: postgres:13
    volumes:
        - "./containers/airflow/pgdata:/var/lib/postgresql/data:rw"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 5s
      retries: 5
    restart: always
    mem_limit: 2gb
    cpu_count: ${CPU_COUNT}
    cpus: 0.7
    ports:
      - "5432:5432"

  dashboard:
    container_name: dashboard
    build:
      context: ./containers/metabase/
    restart: always
    mem_limit: 4gb
    cpu_count: ${CPU_COUNT}
    cpus: 0.7
    volumes:
      - ./containers/metabase/metabase-data:/metabase-data
      - ./database/web-scraping.db:/metabase-data/web-scraping.db
    ports:
      - "3000:3000"

  minio:
    container_name: minio-data-lake
    image: minio/minio:RELEASE.2023-10-07T15-07-38Z
    restart: always
    mem_limit: 1gb
    cpu_count: ${CPU_COUNT}
    cpus: 0.7
    ports:
      - "4144:4144"
      - "4145:4145"
    volumes:
      - ./containers/minio/storage:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --address ":4144" --console-address ":4145" /data
    
networks:
  default:
    name: ${DOCKER_NETWORK}
    external: True

